# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_program_window_new.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UpdateProgram(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(385, 339)
        Dialog.setStyleSheet("background-color: rgba(31,31,47,255)\n"
"")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(21, 98, 140, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:white;")
        self.label_3.setObjectName("label_3")
        self.updateProgramName_box = QtWidgets.QLineEdit(Dialog)
        self.updateProgramName_box.setGeometry(QtCore.QRect(168, 98, 205, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.updateProgramName_box.setFont(font)
        self.updateProgramName_box.setStyleSheet("border-radius: 10px;\n"
"background-color: rgba(44,44,45,255);\n"
"color:white;")
        self.updateProgramName_box.setText("")
        self.updateProgramName_box.setObjectName("updateProgramName_box")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(21, 135, 124, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:white;")
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(170, 20, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setStyleSheet("border-radius: 10px;\n"
"color: white;")
        self.label.setObjectName("label")
        self.updateProgramCode_box = QtWidgets.QLineEdit(Dialog)
        self.updateProgramCode_box.setGeometry(QtCore.QRect(168, 61, 205, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.updateProgramCode_box.setFont(font)
        self.updateProgramCode_box.setStyleSheet("border-radius: 10px;\n"
"background-color: rgba(44,44,45,255);\n"
"color:white;")
        self.updateProgramCode_box.setText("")
        self.updateProgramCode_box.setObjectName("updateProgramCode_box")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(21, 61, 133, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white;")
        self.label_2.setObjectName("label_2")
        self.updateProgram_button = QtWidgets.QPushButton(Dialog)
        self.updateProgram_button.setGeometry(QtCore.QRect(150, 260, 101, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.updateProgram_button.setFont(font)
        self.updateProgram_button.setStyleSheet("background-color: rgb(114,137,218);\n"
"color: white;\n"
"font-weight: bold;\n"
"border-radius: 13px;")
        self.updateProgram_button.setObjectName("updateProgram_button")
        self.updateCollegeCode_box = QtWidgets.QComboBox(Dialog)
        self.updateCollegeCode_box.setGeometry(QtCore.QRect(168, 135, 95, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.updateCollegeCode_box.setFont(font)
        self.updateCollegeCode_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.updateCollegeCode_box.setStyleSheet("border-radius: 10px;\n"
"background-color: rgba(44,44,45,255);\n"
"color:white;")
        self.updateCollegeCode_box.setObjectName("updateCollegeCode_box")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "Program Name:"))
        self.label_4.setText(_translate("Dialog", "College Code:"))
        self.label.setText(_translate("Dialog", "EDIT"))
        self.label_2.setText(_translate("Dialog", "Program Code:"))
        self.updateProgram_button.setText(_translate("Dialog", "Update"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_UpdateProgram()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
