# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_college_window_new.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UpdateCollege(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setStyleSheet("background-color: rgba(31,31,47,255)")
        self.updateCollegeCode_box = QtWidgets.QLineEdit(Dialog)
        self.updateCollegeCode_box.setGeometry(QtCore.QRect(178, 51, 205, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.updateCollegeCode_box.setFont(font)
        self.updateCollegeCode_box.setStyleSheet("border-radius: 10px;\n"
"background-color: rgba(44,44,45,255);\n"
"color:white;")
        self.updateCollegeCode_box.setText("")
        self.updateCollegeCode_box.setObjectName("updateCollegeCode_box")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(31, 51, 133, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(31, 88, 140, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:white;")
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(180, 10, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setStyleSheet("color:white;")
        self.label.setObjectName("label")
        self.updateCollegeName_box = QtWidgets.QLineEdit(Dialog)
        self.updateCollegeName_box.setGeometry(QtCore.QRect(178, 88, 205, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.updateCollegeName_box.setFont(font)
        self.updateCollegeName_box.setStyleSheet("border-radius: 10px;\n"
"background-color: rgba(44,44,45,255);\n"
"color:white;")
        self.updateCollegeName_box.setText("")
        self.updateCollegeName_box.setObjectName("updateCollegeName_box")
        self.updateCollege_button = QtWidgets.QPushButton(Dialog)
        self.updateCollege_button.setGeometry(QtCore.QRect(160, 250, 101, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.updateCollege_button.setFont(font)
        self.updateCollege_button.setStyleSheet("background-color: rgb(114,137,218);\n"
"color: white;\n"
"font-weight: bold;\n"
"border-radius: 13px;")
        self.updateCollege_button.setObjectName("updateCollege_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "College Code:"))
        self.label_3.setText(_translate("Dialog", "College Name:"))
        self.label.setText(_translate("Dialog", "EDIT"))
        self.updateCollege_button.setText(_translate("Dialog", "Update"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_UpdateCollege()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
